# Generated by Django 4.2.21 on 2025-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular'), ('Basic', 'Basic')], default='Regular', max_length=10),
        ),
    ]
