# Generated by Django 4.2.21 on 2025-06-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular'), ('Basic', 'Basic')], default='Basic', max_length=10),
        ),
    ]
