# Generated by Django 4.2.21 on 2025-06-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.profile'),
        ),
    ]
